version: 2.1
orbs:
  snyk: snyk/snyk@1.1.1

workflows: #creating a workflow to define the context - collection of different jobs
  test-env-vars: #setting up a job to define the context which this project will use
    jobs:
      - build-test-monitor-app: #building the relevant context
          context: Snyk  # has an env var called Snyk-Token
      - build-test-monitor-docker: 
          context: Snyk


jobs: # a collection of steps
  build-test-monitor-app: # runs not using Workflows must have a `build` job as entry point #directory where steps will run
    working_directory: ~/goof  
    docker:       
      - image: 'cimg/node:lts'      
    steps:  
       - checkout
       - run: npm ci
       - snyk/scan:
                fail-on-issues: false
                monitor-on-build: true
                token-variable: SNYKTOKEN
                organization: ninja-snyker
                project: circleCi-goof
                severity-threshold: high

  
  build-test-monitor-docker: # runs not using Workflows must have a `build` job as entry point #directory where steps will run
    #working_directory: ~/goof  
    docker:       
      - image: node:current-alpine3.14       
    environment: 
      IMAGE_NAME: akanchhaS/goof
    steps:  
      - checkout  
      - setup_remote_docker   
      - run: 
         name: echo "Build Docker image"  
         command: 'docker build -t my-new-container-circleci-goof-image .'
      - snyk/scan:
                fail-on-issues: false
                monitor-on-build: true
                token-variable: SNYKTOKEN
                organization: ninja-snyker
                project: circleCi-goof-container
                severity-threshold: low
                target-file: Dockerfile
                docker-image-name: my-new-container-circleci-goof-image
                install-alpine-dependencies: true
docker:
  - image: 'snyk/snyk-cli:npm'
parameters:
  args:
    default: ''
    description: >
      See the Snyk CLI help page for information on additional arguments:
      https://support.snyk.io/hc/en-us/articles/360003812578-CLI-reference
    type: string
resource_class: medium
steps:
  - checkout
  - scan:
      additional-arguments: ' '
      command: iac test
      monitor-on-build: false

#workflows:
  #node-tests:
    #jobs:
     # - node/test
      #- snyk/scan:
       #         fail-on-issues: false
        #        monitor-on-build: true
         #       token-variable: SNYKTOKEN
          #      organization: panda-not-omar
           #     project: circleCi-dotnet-goof